const tracks=[
  {id:"kick",name:"Kick",type:"kick",color:"#e95850",steps:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0]},
  {id:"clap",name:"Clap",type:"clap",color:"#f6921e",steps:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0]},
  {id:"hat",name:"Hi-hat",type:"hat",color:"#ffca3a",steps:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]},
  {id:"bass",name:"Bass",type:"bass",color:"#69bb6e",steps:[1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0]},
  {id:"chime",name:"Chime",type:"chime",color:"#2c91d0",steps:[0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0]}
];
const sounds=[{id:"chime",name:"Chime",hint:"bright melody",color:"#2c91d0"},{id:"marimba",name:"Marimba",hint:"warm wood",color:"#e95850"},{id:"synth",name:"Synth",hint:"soft pad",color:"#8963bc"},{id:"bass",name:"Bass",hint:"deep groove",color:"#69bb6e"},{id:"drums",name:"Drums",hint:"beat kit",color:"#f6921e"}];
const keys=["C4","D4","E4","F4","G4","A4","B4","C5","D5"];
let audioContext,master,playing=false,timer,position=0,selectedSound="chime",toastTimer;
const $=id=>document.getElementById(id);
function initAudio(){if(audioContext)return;audioContext=new (window.AudioContext||window.webkitAudioContext)();master=audioContext.createGain();master.gain.value=.48;master.connect(audioContext.destination)}
function hz(note){const map={C:-9,D:-7,E:-5,F:-4,G:-2,A:0,B:2};const m=note.match(/([A-G])(#?)(\d)/);return 440*Math.pow(2,(map[m[1]]+(m[2]?1:0)+(Number(m[3])-4)*12)/12)}
function tone(freq,duration,kind="chime",volume=.16,when=0){initAudio();const t=audioContext.currentTime+when,g=audioContext.createGain(),filter=audioContext.createBiquadFilter();filter.type="lowpass";filter.frequency.value=kind==="bass"?700:5000;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);filter.connect(g).connect(master);const add=(wave,mul,detune=0)=>{const o=audioContext.createOscillator();o.type=wave;o.frequency.setValueAtTime(freq*mul,t);o.detune.value=detune;o.connect(filter);o.start(t);o.stop(t+duration+.03)};if(kind==="chime"){add("sine",1);add("sine",2.01,4);add("sine",3.02,-5)}else if(kind==="marimba"){add("triangle",1);add("sine",3.2)}else if(kind==="synth"){add("sawtooth",1,-8);add("sawtooth",1,8)}else if(kind==="bass"){add("sawtooth",1);add("sine",.5)}else add("triangle",1)}
function noise(duration,volume,when=0,bright=false){initAudio();const t=audioContext.currentTime+when,b=audioContext.createBuffer(1,Math.ceil(audioContext.sampleRate*duration),audioContext.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const src=audioContext.createBufferSource(),g=audioContext.createGain(),f=audioContext.createBiquadFilter();f.type="highpass";f.frequency.value=bright?6000:1200;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.buffer=b;src.connect(f).connect(g).connect(master);src.start(t)}
function drum(type,when=0){initAudio();const t=audioContext.currentTime+when;if(type==="kick"){const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.setValueAtTime(150,t);o.frequency.exponentialRampToValueAtTime(48,t+.18);g.gain.setValueAtTime(.65,t);g.gain.exponentialRampToValueAtTime(.0001,t+.21);o.connect(g).connect(master);o.start(t);o.stop(t+.22)}else if(type==="clap"){[0,.025,.05].forEach(x=>noise(.08,.2,when+x));}else noise(.045,.1,when,true)}
function playTrack(track,step){if(!track.steps[step])return;if(track.type==="kick"||track.type==="clap"||track.type==="hat")drum(track.type);else if(track.type==="bass")tone(hz(["C2","C2","G1","C2"][Math.floor(step/4)]),.25,"bass",.2);else tone(hz(["E5","G5","A5","G5"][Math.floor(step/4)]),.3,"chime",.1)}
function renderSounds(){const box=$("soundChoices");box.innerHTML="";sounds.forEach(sound=>{const b=document.createElement("button");b.type="button";b.className="sound-choice"+(sound.id===selectedSound?" active":"");b.style.setProperty("--choice",sound.color);b.innerHTML=`<b>${sound.name}</b><small>${sound.hint}</small>`;b.onclick=()=>{selectedSound=sound.id;renderSounds();say(`${sound.name} selected`)};box.append(b)})}
function renderGrid(){const box=$("sequencer");box.innerHTML="";tracks.forEach(track=>{const label=document.createElement("div");label.className="track-name";label.innerHTML=`<i class="track-dot" style="--track:${track.color}"></i>${track.name}`;box.append(label);track.steps.forEach((on,index)=>{const b=document.createElement("button");b.type="button";b.className="step"+(on?" on":"");b.style.setProperty("--track",track.color);b.setAttribute("aria-label",`${track.name}, beat ${index+1}`);b.dataset.track=track.id;b.dataset.step=index;b.onclick=()=>{track.steps[index]=track.steps[index]?0:1;renderGrid();if(track.steps[index])preview(track)};box.append(b)})})}
function preview(track){if(track.type==="kick"||track.type==="clap"||track.type==="hat")drum(track.type);else if(track.type==="bass")tone(hz("C2"),.3,"bass",.2);else tone(hz("C5"),.35,"chime",.13)}
function tick(){document.querySelectorAll(".step.current").forEach(x=>x.classList.remove("current"));document.querySelectorAll(`.step[data-step="${position}"]`).forEach(x=>x.classList.add("current"));tracks.forEach(track=>playTrack(track,position));$("beatNumber").textContent=position+1;position=(position+1)%16}
function togglePlay(){initAudio();if(audioContext.state==="suspended")audioContext.resume();playing=!playing;const button=$("playButton");button.classList.toggle("playing",playing);button.innerHTML=playing?"<span>■</span> Stop":"<span>▶</span> Play";if(playing){tick();timer=setInterval(tick,60000/Number($("tempo").value)/4)}else{clearInterval(timer);document.querySelectorAll(".step.current").forEach(x=>x.classList.remove("current"));$("beatNumber").textContent="Ready"}}
function setPattern(name){const patterns={pop:[[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],[1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0],[0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0]],dance:[[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,0,0,0,1,0,1,0,1,0,0,0,1,0,1,0],[0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1]],chill:[[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],[0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0],[1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]]};tracks.forEach((track,i)=>track.steps=[...patterns[name][i]]);renderGrid();say(`${name[0].toUpperCase()+name.slice(1)} beat loaded`)}
function renderWav(){const rate=44100,stepSeconds=60/Number($("tempo").value)/4,length=Math.ceil((stepSeconds*16+.5)*rate),data=new Float32Array(length);const add=(start,seconds,make,volume=.18)=>{const from=Math.floor(start*rate),to=Math.min(length,from+Math.floor(seconds*rate));for(let i=from;i<to;i++){const age=(i-from)/rate;data[i]+=make(age,seconds)*volume}};tracks.forEach(track=>track.steps.forEach((on,step)=>{if(!on)return;const start=step*stepSeconds;if(track.type==="kick")add(start,.23,age=>Math.sin(2*Math.PI*(150-450*age)*age)*Math.exp(-age*17),.8);else if(track.type==="clap")for(const offset of [0,.028,.055])add(start+offset,.09,(age,seconds)=>(Math.random()*2-1)*(1-age/seconds),.15);else if(track.type==="hat")add(start,.055,(age,seconds)=>(Math.random()*2-1)*(1-age/seconds),.1);else if(track.type==="bass"){const f=step<8?65.41:49;add(start,.28,age=>(Math.sin(2*Math.PI*f*age)+.25*Math.sin(2*Math.PI*f*2*age))*Math.exp(-age*5),.22)}else{const f=[659.25,783.99,880,783.99][Math.floor(step/4)];add(start,.35,age=>(Math.sin(2*Math.PI*f*age)+.3*Math.sin(2*Math.PI*f*2.01*age))*Math.exp(-age*7),.13)}}));const buffer=new ArrayBuffer(44+length*2),view=new DataView(buffer),write=(offset,text)=>[...text].forEach((char,i)=>view.setUint8(offset+i,char.charCodeAt(0)));write(0,"RIFF");view.setUint32(4,36+length*2,true);write(8,"WAVE");write(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,length*2,true);for(let i=0;i<length;i++)view.setInt16(44+i*2,Math.max(-1,Math.min(1,data[i]))*32767,true);return new Blob([buffer],{type:"audio/wav"})}
function downloadSong(){const url=URL.createObjectURL(renderWav()),link=document.createElement("a");link.href=url;link.download="my-music-maker-beat.wav";link.style.display="none";document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say("Your WAV download is ready!")}
function playKey(note,index,element){if(selectedSound==="drums")drum(index%3===0?"kick":index%3===1?"clap":"hat");else tone(hz(note),selectedSound==="synth"?.75:.42,selectedSound,.15);element?.classList.add("active");setTimeout(()=>element?.classList.remove("active"),130)}
function renderKeys(){const box=$("keys");keys.forEach((note,index)=>{const b=document.createElement("button");b.type="button";b.className="key";b.style.setProperty("--key",sounds[index%4].color);b.textContent=note; b.onclick=()=>playKey(note,index,b);box.append(b)})}
function say(text){clearTimeout(toastTimer);$("toast").textContent=text;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),1800)}
$("playButton").onclick=togglePlay;$("clearButton").onclick=()=>{tracks.forEach(track=>track.steps.fill(0));renderGrid();say("Your beat grid is clear")};$("downloadButton").onclick=downloadSong;$("tempo").oninput=e=>{$("tempoValue").value=e.target.value;if(playing){clearInterval(timer);timer=setInterval(tick,60000/Number(e.target.value)/4)}};document.querySelectorAll("[data-pattern]").forEach(button=>button.onclick=()=>setPattern(button.dataset.pattern));$("challengeButton").onclick=()=>{setPattern("chill");$("tempo").value=82;$("tempo").dispatchEvent(new Event("input"));say("Rain challenge loaded — change it any way you like!")};$("helpButton").onclick=()=>say("Pick a sound, click beat boxes, and press Play!");document.addEventListener("keydown",event=>{if(event.repeat)return;const index="asdfghjkl".indexOf(event.key.toLowerCase());if(index>=0)playKey(keys[index],index,document.querySelectorAll(".key")[index]);if(event.code==="Space"){event.preventDefault();togglePlay()}});renderSounds();renderGrid();renderKeys();
