const AC=window.AudioContext||window.webkitAudioContext;let ctx=null,master=null,playing=false,recording=false,timer=null,raf=null,playSec=0,step=0,selectedTrack="piano",importedBuffer=null,history=[],future=[],zoom=1;
const KEY="rohansMusicStudioV5";const tracks=[["drums","Drums","Drum Kit"],["bass","Bass","808 Bass"],["piano","Piano","Grand Piano"],["melody","Melody","Synth Lead"]];const notes=["C3","D3","E3","F3","G3","A3","B3","C4","D4","E4","F4","G4","A4","B4","C5","D5"];
const packs={"Pop Essentials":{bpm:118,drums:[0,4,8,12],snare:[4,12],hat:[0,2,4,6,8,10,12,14],bass:[0,4,8,12],piano:[0,4,8,12],melody:[2,6,10,14]},"EDM Energy":{bpm:128,drums:[0,2,4,6,8,10,12,14],snare:[4,12],hat:[1,3,5,7,9,11,13,15],bass:[0,2,4,6,8,10,12,14],piano:[0,4,8,12],melody:[3,7,11,15]},"Lo-Fi Dreams":{bpm:86,drums:[0,7,8,14],snare:[4,12],hat:[2,6,10,14],bass:[0,6,8,14],piano:[0,5,9,13],melody:[2,8,12]},"Rock Room":{bpm:108,drums:[0,4,8,12],snare:[4,12],hat:[0,2,4,6,8,10,12,14],bass:[0,4,8,12],piano:[0,4,8,12],melody:[0,8]}};
function fresh(){return{name:"My Music",bpm:120,lengthBars:32,clips:[],roll:{}}}let project=JSON.parse(localStorage.getItem(KEY)||"null")||fresh();function clone(){return JSON.parse(JSON.stringify(project))}function snap(){history.push(JSON.stringify(project));if(history.length>30)history.shift();future=[]}function save(){localStorage.setItem(KEY,JSON.stringify(project));snap();state("Saved")}
function state(s){document.getElementById("state").textContent=s;document.getElementById("statusText").textContent=s}
function audio(){if(!ctx){ctx=new AC();master=ctx.createGain();master.gain.value=.8;master.connect(ctx.destination)}if(ctx.state==="suspended")ctx.resume();return ctx}
function freq(n){const m=n.match(/^([A-G])([#b]?)(-?\d)$/);if(!m)return 261.63;const z={C:0,D:2,E:4,F:5,G:7,A:9,B:11};return 440*Math.pow(2,(z[m[1]]+(m[2]==="#"?1:m[2]==="b"?-1:0)+(+m[3]-4)*12-9)/12)}
function synth(n,d,v,eng="piano",when=0,dest=null){audio();dest=dest||master;const t=ctx.currentTime+when,f=freq(n),g=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.value=eng==="bass"?900:7000;g.gain.setValueAtTime(.0001,t);const os=[];const add=(w,m,det=0)=>{const o=ctx.createOscillator();o.type=w;o.frequency.value=f*m;o.detune.value=det;o.connect(filter);o.start(t);o.stop(t+d+.1);os.push(o)};if(eng==="piano"){add("triangle",1);add("sine",2,3)}else if(eng==="electric"){add("sine",1);add("triangle",2,5)}else if(eng==="bass"){add("sawtooth",1);add("sine",.5)}else if(eng==="lead"){add("sawtooth",1);add("square",2,-7)}else if(eng==="pad"){add("sawtooth",1,-9);add("sawtooth",1,9)}else if(eng==="strings"){add("sawtooth",1,-5);add("sawtooth",1,5)}else if(eng==="guitar"){add("triangle",1);add("square",2,-12)}else if(eng==="organ"){add("sine",1);add("sine",2);add("sine",3)}else if(eng==="bell"){add("sine",1);add("sine",2.7);add("sine",4.1)}else add("triangle",1);filter.connect(g).connect(dest);g.gain.exponentialRampToValueAtTime(Math.max(.002,v),t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+d+.18)}
function noise(d,v,when=0,dest=null){audio();dest=dest||master;const b=ctx.createBuffer(1,Math.floor(ctx.sampleRate*d),ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=b;g.gain.setValueAtTime(v,ctx.currentTime+when);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+when+d);s.connect(g).connect(dest);s.start(ctx.currentTime+when)}
function drum(k,when=0){if(k==="kick"){audio();const t=ctx.currentTime+when,o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(145,t);o.frequency.exponentialRampToValueAtTime(45,t+.18);g.gain.setValueAtTime(.8,t);g.gain.exponentialRampToValueAtTime(.0001,t+.3);o.connect(g).connect(master);o.start(t);o.stop(t+.32)}else noise(k==="hat"?.05:.14,k==="hat"?.12:.27,when)}
function engine(i){return({"Grand Piano":"piano","Electric Piano":"electric","808 Bass":"bass","Drum Kit":"drums","Synth Lead":"lead","Synth Pad":"pad","Strings":"strings","Guitar":"guitar","Organ":"organ","Bell":"bell"})[i]||"piano"}
function clipAt(sec){return project.clips.filter(c=>sec>=c.start&&sec<c.start+c.length)}
function playClip(c,local){const s=local*4;const p=c.pattern;if(c.track==="drums"&&p.drums.includes(s%16))drum("kick");if(c.track==="drums"&&p.snare.includes(s%16))drum("snare");if(c.track==="drums"&&p.hat.includes(s%16))drum("hat");if(c.track==="bass"&&p.bass.includes(s%16))synth(["C2","G1","A1","F1"][Math.floor((s%16)/4)],.35,.16,"bass");if(c.track==="piano"&&p.piano.includes(s%16))synth(["C4","E4","G4","B4"][Math.floor((s%16)/4)],.5,.16,engine(c.instrument));if(c.track==="melody"&&p.melody.includes(s%16))synth(["E5","G5","A5","B5","D6"][Math.floor((s%16)/2)%5],.32,.11,"lead")}
function tick(){const beat=60/project.bpm;playSec+=beat/4;step=(step+1)%16;clipAt(playSec).forEach(c=>playClip(c,playSec-c.start));renderTimeline();timecode();if(playSec>=project.lengthBars*4){stop()}}
function start(){audio();if(playing)return;playing=true;state(recording?"Recording":"Playing");tick();timer=setInterval(tick,60000/project.bpm/4)}
function stop(){playing=false;clearInterval(timer);timer=null;state(recording?"Recording stopped":"Stopped");if(recording){recording=false;document.getElementById("record").textContent="Record"}}
function toggleRecord(){audio();if(recording){recording=false;document.getElementById("record").textContent="Record";state("Recording stopped");return}recording=true;playSec=0;document.getElementById("record").textContent="Stop Recording";state("Recording");if(!playing)start()}
function addClip(track,start,pattern,instrument=selectedInstrument()){project.clips.push({id:Date.now()+Math.random(),track,start,length:4,pattern:JSON.parse(JSON.stringify(pattern)),instrument});snap();renderTimeline();state("Clip recorded on timeline")}
function selectedInstrument(){return document.getElementById("instrumentSelect").value}
function defaultPattern(){return{drums:[0,4,8,12],snare:[4,12],hat:[0,2,4,6,8,10,12,14],bass:[0,4,8,12],piano:[0,4,8,12],melody:[2,6,10,14]}}
function renderTimeline(){const tl=document.getElementById("timeline"),labels=document.getElementById("trackLabels");tl.innerHTML="";labels.innerHTML="";const ruler=document.createElement("div");ruler.className="ruler";for(let i=1;i<=32;i++){const s=document.createElement("span");s.textContent=i;ruler.append(s)}tl.append(ruler);tracks.forEach(t=>{const l=document.createElement("div");l.className="tl-label";l.textContent=t[1];labels.append(l);const lane=document.createElement("div");lane.className="lane";lane.dataset.track=t[0];for(let i=0;i<32;i++){const hit=document.createElement("div");hit.dataset.bar=i;hit.onclick=()=>{if(project.clips.some(c=>c.track===t[0]&&c.start===i*4))return;addClip(t[0],i*4,defaultPattern(),t[2])};lane.append(hit)}project.clips.filter(c=>c.track===t[0]).forEach(c=>{const b=document.createElement("div");b.className="bar "+t[0];b.style.gridColumn=(c.start/4+1)+"/span "+Math.max(1,c.length/4);b.textContent=t[1]+" • "+Math.floor(c.start/4+1);b.title="Click to remove clip";b.onclick=e=>{e.stopPropagation();project.clips=project.clips.filter(x=>x.id!==c.id);snap();renderTimeline();state("Clip removed")};lane.append(b)});tl.append(lane)});const ph=document.createElement("div");ph.className="playhead";ph.style.left=(playSec/(project.lengthBars*4))*100+"%";tl.append(ph)}
function renderTracks(){const box=document.getElementById("tracks");box.innerHTML="";tracks.forEach(t=>{const d=document.createElement("div");d.className="track"+(selectedTrack===t[0]?" active":"");d.innerHTML="<b>"+t[1]+"</b><small>"+t[2]+"</small>";d.onclick=()=>{selectedTrack=t[0];document.getElementById("selectedTrackTitle").textContent=t[1];renderTracks()};box.append(d)})}
function renderInstruments(){const box=document.getElementById("instrumentCards");box.innerHTML="";["Grand Piano","Electric Piano","808 Bass","Drum Kit","Synth Lead","Synth Pad","Strings","Guitar","Organ","Bell"].forEach(n=>{const d=document.createElement("div");d.className="instrument";d.innerHTML="<b>"+n+"</b><small>Built-in instrument</small>";d.onclick=()=>{document.getElementById("instrumentSelect").value=n;state(n+" selected")};box.append(d)})}
function renderPacks(){const box=document.getElementById("soundPacks");box.innerHTML="";Object.entries(packs).forEach(([n,p])=>{const d=document.createElement("div");d.className="pack";d.innerHTML="<b>"+n+"</b><small>"+p.bpm+" BPM</small>";d.onclick=()=>{document.getElementById("bpm").value=p.bpm;state(n+" ready — click a timeline bar to place it")};box.append(d)})}
function renderLoops(){const box=document.getElementById("loopLibrary");box.innerHTML="";["Intro","Verse","Chorus","Bridge","Outro"].forEach((n,i)=>{const d=document.createElement("div");d.className="loop";d.innerHTML="<b>"+n+"</b><small>4-bar clip</small>";d.onclick=()=>{const start=i*4;if(!project.clips.some(c=>c.start===start&&c.track===selectedTrack))addClip(selectedTrack,start,defaultPattern(),selectedInstrument())};box.append(d)})}
function renderRoll(){const box=document.getElementById("pianoRoll");box.innerHTML="";notes.slice().reverse().forEach(n=>{const l=document.createElement("div");l.className="roll-label";l.textContent=n;box.append(l);for(let i=0;i<16;i++){const b=document.createElement("button");b.className="roll-cell";b.onclick=()=>{const sec=playSec;const bar=Math.floor(sec/4)*4;const p=defaultPattern();if(selectedTrack==="piano")p.piano=[i];if(selectedTrack==="melody")p.melody=[i];addClip(selectedTrack,bar,p,selectedInstrument());synth(n,.35,.12,engine(selectedInstrument()));renderRoll()};box.append(b)}})}
function renderKeys(){const box=document.getElementById("keys");box.innerHTML="";["C4","D4","E4","F4","G4","A4","B4","C5","D5"].forEach(n=>{const b=document.createElement("button");b.className="key";b.textContent=n;b.onpointerdown=()=>{synth(n,.6,.18,engine(selectedInstrument()));if(recording)addClip(selectedTrack,Math.floor(playSec/4)*4,defaultPattern(),selectedInstrument());b.classList.add("active")};b.onpointerup=()=>b.classList.remove("active");box.append(b)})}
function renderPads(){const box=document.getElementById("pads");box.innerHTML="";["Kick","Snare","Hat","Clap","Bass","Piano","Synth","Chord"].forEach(n=>{const b=document.createElement("button");b.className="pad";b.textContent=n;b.onclick=()=>{if(n==="Kick"||n==="Snare"||n==="Hat"||n==="Clap")drum(n.toLowerCase());else if(n==="Bass")synth("C2",.5,.2,"bass");else if(n==="Piano")synth("C4",.7,.18,"piano");else if(n==="Synth")synth("G4",.5,.15,"lead");else ["C4","E4","G4"].forEach(x=>synth(x,.7,.1,"piano"));if(recording)addClip(selectedTrack,Math.floor(playSec/4)*4,defaultPattern(),selectedInstrument());b.classList.add("hit");setTimeout(()=>b.classList.remove("hit"),100)};box.append(b)})}
function render(){document.getElementById("projectTitle").textContent=project.name;document.getElementById("projectName").value=project.name;document.getElementById("bpm").value=project.bpm;const ins=["Grand Piano","Electric Piano","808 Bass","Drum Kit","Synth Lead","Synth Pad","Strings","Guitar","Organ","Bell"];document.getElementById("instrumentSelect").innerHTML=ins.map(x=>"<option>"+x+"</option>").join("");renderTracks();renderInstruments();renderPacks();renderLoops();renderRoll();renderKeys();renderPads();renderTimeline();timecode()}
function timecode(){const m=Math.floor(playSec/60).toString().padStart(2,"0"),s=Math.floor(playSec%60).toString().padStart(2,"0");document.getElementById("timecode").textContent=m+":"+s}
function offline(seconds){const sr=44100,o=new OfflineAudioContext(2,Math.ceil(sr*seconds),sr),mg=o.createGain();mg.gain.value=+document.getElementById("masterVol").value/100;mg.connect(o.destination);const ot=(n,t,d,v,e)=>{const f=freq(n),g=o.createGain(),q=o.createOscillator();q.type=e==="bass"?"sawtooth":"triangle";q.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.02);g.gain.exponentialRampToValueAtTime(.0001,Math.min(seconds,t+d+.2));q.connect(g).connect(mg);q.start(t);q.stop(Math.min(seconds,t+d+.25))};const beat=60/project.bpm/4;for(const c of project.clips){for(let s=0;s<16;s++){const t=c.start+s*beat;if(t>=seconds)continue;if(c.track==="drums"&&c.pattern.drums.includes(s)){}if(c.track==="bass"&&c.pattern.bass.includes(s))ot(["C2","G1","A1","F1"][Math.floor(s/4)],t,.35,.16,"bass");if(c.track==="piano"&&c.pattern.piano.includes(s))ot(["C4","E4","G4","B4"][Math.floor(s/4)],t,.5,.15,"piano");if(c.track==="melody"&&c.pattern.melody.includes(s))ot(["E5","G5","A5","B5"][Math.floor(s/2)%4],t,.32,.1,"lead")}}return o.startRendering()}
function wav(b){const ch=b.numberOfChannels,rate=b.sampleRate,len=b.length*ch*2,buf=new ArrayBuffer(44+len),v=new DataView(buf),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,"RIFF");v.setUint32(4,36+len,true);w(8,"WAVEfmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,"data");v.setUint32(40,len,true);let p=44;for(let i=0;i<b.length;i++)for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([buf],{type:"audio/wav"})}
function dl(b,n){const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function exportWav(){state("Rendering song WAV...");const b=await offline(Math.max(4,project.lengthBars*4*60/project.bpm));dl(wav(b),"rohan-song.wav");state("WAV downloaded")}
async function exportMp3(){if(!window.lamejs){state("MP3 encoder unavailable");return}state("Rendering song MP3...");const b=await offline(Math.max(4,project.lengthBars*4*60/project.bpm)),L=b.getChannelData(0),R=b.getChannelData(1),e=new lamejs.Mp3Encoder(2,b.sampleRate,192),out=[];for(let i=0;i<L.length;i+=1152){const n=Math.min(1152,L.length-i),l=new Int16Array(n),r=new Int16Array(n);for(let j=0;j<n;j++){l[j]=L[i+j]*32767;r[j]=R[i+j]*32767}const x=e.encodeBuffer(l,r);if(x.length)out.push(new Uint8Array(x))}const z=e.flush();if(z.length)out.push(new Uint8Array(z));dl(new Blob(out,{type:"audio/mpeg"}),"rohan-song.mp3");state("MP3 downloaded")}
function setup(){document.getElementById("play").onclick=start;document.getElementById("stop").onclick=stop;document.getElementById("record").onclick=toggleRecord;document.getElementById("rewind").onclick=()=>{playSec=0;renderTimeline();timecode()};document.getElementById("save").onclick=save;document.getElementById("newProject").onclick=()=>{project=fresh();const n=prompt("Song name","My New Song");if(n)project.name=n;render();save()};document.getElementById("duplicateProject").onclick=()=>{project={...clone(),name:project.name+" Copy",clips:project.clips.map(c=>({...c,id:Date.now()+Math.random()}))};render();save()};document.getElementById("deleteProject").onclick=()=>{project=fresh();render();save()};document.getElementById("projectName").oninput=e=>{project.name=e.target.value;document.getElementById("projectTitle").textContent=project.name;localStorage.setItem(KEY,JSON.stringify(project))};document.getElementById("bpm").oninput=e=>{project.bpm=Math.max(50,Math.min(200,+e.target.value||120));localStorage.setItem(KEY,JSON.stringify(project))};document.getElementById("masterVol").oninput=e=>{audio();master.gain.value=+e.target.value/100};document.getElementById("fullscreen").onclick=()=>document.documentElement.requestFullscreen?.();document.getElementById("clearSong").onclick=()=>{project.clips=[];renderTimeline();save()};document.getElementById("zoomIn").onclick=()=>{zoom=Math.min(1.5,zoom+.1);document.querySelector(".timeline").style.minWidth=(1100*zoom)+"px"};document.getElementById("zoomOut").onclick=()=>{zoom=Math.max(.7,zoom-.1);document.querySelector(".timeline").style.minWidth=(1100*zoom)+"px"};document.getElementById("instrumentSelect").onchange=()=>state(document.getElementById("instrumentSelect").value+" selected");document.getElementById("exportWav").onclick=exportWav;document.getElementById("exportMp3").onclick=exportMp3;document.getElementById("random").onclick=()=>{project.clips=[];for(let i=0;i<8;i++)addClip(tracks[i%4][0],i*4,defaultPattern(),tracks[i%4][2]);renderTimeline();state("Arrangement generated")};document.getElementById("audio").onchange=async e=>{const f=e.target.files[0];if(!f)return;audio();try{importedBuffer=await ctx.decodeAudioData(await f.arrayBuffer());document.getElementById("audioName").textContent=f.name;state("Audio loaded")}catch{state("Audio could not be decoded")}};document.getElementById("playImported").onclick=()=>{if(!importedBuffer)return state("Import an audio file first");audio();const s=ctx.createBufferSource();s.buffer=importedBuffer;s.connect(master);s.start();state("Imported audio playing")};document.addEventListener("keydown",e=>{if(e.target.matches("input,select"))return;const m={a:"C4",s:"D4",d:"E4",f:"F4",g:"G4",h:"A4",j:"B4",k:"C5",l:"D5"};if(m[e.key]&&!e.repeat){synth(m[e.key],.6,.16,engine(selectedInstrument()));if(recording)addClip(selectedTrack,Math.floor(playSec/4)*4,defaultPattern(),selectedInstrument())}if(e.code==="Space"){e.preventDefault();playing?stop():start()}})}
setup();render();